"""Add stops and route_stops tables

Revision ID: edb60f9515fb
Revises: 6b8c9753559d
Create Date: 2026-07-19 15:43:29.851539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb60f9515fb'
down_revision = '6b8c9753559d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'stop_id', 'day', name='uq_route_stop_day')
    )
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_stops_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_stops_stop_id'), ['stop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_stops_stop_id'))
        batch_op.drop_index(batch_op.f('ix_route_stops_route_id'))

    op.drop_table('route_stops')
    op.drop_table('stops')
    # ### end Alembic commands ###
